# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 730eb81cb3c3928c432feab09bfd9bb8e640129104eceef3a2fdf7488a1ef9dad594f02679ccf94632bc019f752f5748d340196177bf3df71313bd91edb70c55
  marys_group: <%= ENV["marys_group"] %>
  AKIAILXCSGXZGD3XTSOA: <%= ENV["AKIAILXCSGXZGD3XTSOA"] %>
  73PFnaBJtTJ+U0cxlCHV/ATyUwB4MLxHKh2Z2H3l: <%= ENV["73PFnaBJtTJ+U0cxlCHV/ATyUwB4MLxHKh2Z2H3l"] %>
  us-east-2: <%= ENV["us-east-2"] %>

test:
  secret_key_base: 64322197df5529e717400c02dc38cfce657a21f9666470ab1738a56b4117423b8613a3f28605d992609f23eccf13468d7c90924c52c7e8641824b2ee04bb889f
  marys_group: <%= ENV["marys_group"] %>
  AKIAILXCSGXZGD3XTSOA: <%= ENV["AKIAILXCSGXZGD3XTSOA"] %>
  73PFnaBJtTJ+U0cxlCHV/ATyUwB4MLxHKh2Z2H3l: <%= ENV["73PFnaBJtTJ+U0cxlCHV/ATyUwB4MLxHKh2Z2H3l"] %>
  us-east-2: <%= ENV["us-east-2"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  marys_group: <%= ENV["marys_group"] %>
  AKIAILXCSGXZGD3XTSOA: <%= ENV["AKIAILXCSGXZGD3XTSOA"] %>
  73PFnaBJtTJ+U0cxlCHV/ATyUwB4MLxHKh2Z2H3l: <%= ENV["73PFnaBJtTJ+U0cxlCHV/ATyUwB4MLxHKh2Z2H3l"] %>
  us-east-2: <%= ENV["us-east-2"] %>